### ISSUE TITLE
[MacOS] Unable to find required libraries to run embedded mpv player

### ISSUE THREAD

**Issue by hopelesscase** [URUWorks/SubtitleWorkshop#1]
I recently tried to run this for the first time, but met with the alert:
"Unable to find required libraries to run embedded mpv player. Please go and download them."

I installed the mpv cask via homebrew, but I still get the alert so I think I'm missing something.

I recently changed from a really old Windows (barely could run Win 10) to this Mac so I've little to no idea what I'm doing on this thing half the time. Have patience please while I learn. 😅

**Comment by URUWorks** [comment]
Surely it must be a problem with the name of the mpv library file, do you have any idea what it is?

**Comment by URUWorks** [comment]
SW looks for the library file “libmpv.dylib” in “usr/local/lib”, “Desktop/mpv.app/Contents/MacOS" and/or “Applications/mpv.app/Contents/MacOS”,  depending on the version of mpv it may have another name so that should fix in the code :)

**Comment by chenlung** [comment]
> SW looks for the library file “libmpv.dylib” in “usr/local/lib”, “Desktop/mpv.app/Contents/MacOS" and/or “Applications/mpv.app/Contents/MacOS”, depending on the version of mpv it may have another name so that should fix in the code :)

Unless I did something wrong, I don't think this helps. Can anyone else try to be sure?

**Comment by URUWorks** [comment]
I made some changes in the library search code, for the next release I hope it works as it should :)

**Comment by steefdebruijn** [comment]
I installed mpv via brew, now the error message on startup is gone, but as soon as I select my DVD-rip (mkv format) the whole application beachballs until I force stop it.

**Comment by URUWorks** [comment]
Right, I think the hangs is a conflict between mpv and macos, I think it's fixed in version 7.02 r1 using opengl.

**Comment by steefdebruijn** [comment]
Nice; I would like to test that, but the noted version only has a windows binary download. And I have no clue how to build this package myself (no makefile or other build scripts in the repo as far as I can see...)

**Comment by URUWorks** [comment]
These days I will be uploading the Mac binary version to test :)

**Comment by valentibarrios** [comment]
> These days I will be uploading the Mac binary version to test :)

Hi there! Thanks for creating this.
However - I am, too, having trouble opening videos on SW. They just don't open, so I'm unable to work.
Have you been able to solve the issues for SW on mac?

Gracias!

**Comment by URUWorks** [comment]
Fixed in v7.02 r2 with the lib correctly installed.
