### ISSUE TITLE
[discussion] Is another name being considered for the software? 

### ISSUE THREAD

**Issue by wcxu21** [URUWorks/SubtitleWorkshop#10]
Hi, dear developer. 
Thank you very much for your contribution to open source applications. 
There is already an open source subtitle app with the same name, would you consider changing the name to avoid confusion?
https://subworkshop.sourceforge.net/index.php

**Comment by aifuenzalida** [comment]
The Subtitle Workshop from Uruworks was the first.
First proof: https://hipertextual.com/2009/09/bitelia-responde-combinar-archivos-de-video-y-subtitulos (in the comments in 2009 make a reference)
Second proof: https://foro.noticias3d.com/vbulletin/archive/index.php?t-377492.html, posted in 2011 and make reference of the origin (Uruguay).
The SF software was created in 2013 and not having more releases. It's dead.
