### ISSUE TITLE
V. 7.02 R1 - Accentdd letters showed wrong

### ISSUE THREAD

**Issue by bovirus** [URUWorks/SubtitleWorkshop#13]
@URUWorks 

I created a new italian language.

In italian language the accented letters like **à è é ì ò ù** are not showed right (also if the files are in UTF-8 text file format).

**Comment by bovirus** [comment]
@URUWorks 

Could you pelase check? Thanks.

**Comment by URUWorks** [comment]
we are going to check it

**Comment by bovirus** [comment]
@URUWorks 

Fixed using language files coded as UTF-8.
