### ISSUE TITLE
english and chindse language file are not aligned as string order/id

### ISSUE THREAD

**Issue by bovirus** [URUWorks/SubtitleWorkshop#14]
@URUWorks 

Please check lng files for english and chinese language.

The two files are not aligned for the same strings and string id.

In chinese language there is a string not available in english language.

In english language there is a string not available in chinese language.

Thanks. KR.

**Comment by Little-Data** [comment]
For language file,it is an issue of **Program**,not language file
对于语言文件，是**程序自身**的问题

**Comment by Little-Data** [comment]
> For language file,it is an issue of **Program**,not language file 对于语言文件，是**程序自身**的问题

In fact, I have no time to update Chinese language file
事实上，我没时间去更新中文语言文件ヾ(•ω•`)o

**Comment by bovirus** [comment]
@Little-Data 

Please check the english and langauge files.
have different string order and different srtrint content.
Which is the master language file? The english one?

**Comment by Little-Data** [comment]
The english one is master language file.
英语是主语言文件。
With different string order and different srtrint content, this is a developer's problem.
对于具有不同的字符串顺序和不同的srtrint内容，这是开发者的问题。
I'm just a translator of simplified Chinese language pack, not a software developer.
我只是简体中文语言包的翻译者，不是软件开发者。
Sorry I can't help you check the English language pack.This language pack is made by the software owner.
抱歉，我无法帮助你检查英语语言包。此语言包由软件所有者制作。(⋟﹏⋞)

**Comment by bovirus** [comment]
@URUWorks 

I already re-aligned all language file (english/chinese/italian) also adding "Cancel" text for button in "Create new project" window.

We can close this ticket.
