### ISSUE TITLE
[UI] Multiple issues

### ISSUE THREAD

**Issue by bovirus** [URUWorks/SubtitleWorkshop#15]
@URUWorks 

Please check screenshots about GUI issues

![Subtitle Workshop 7 02 R1 - GUI - 01](https://user-images.githubusercontent.com/1262554/197861084-9704bede-0659-472c-a2cb-64fc3e5938e5.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 02](https://user-images.githubusercontent.com/1262554/197861091-06ddf262-294f-4238-9dcc-6ed74437e2e1.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 03](https://user-images.githubusercontent.com/1262554/197861092-411fb426-c61c-4a2c-ba55-2ad629c49f9c.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 04](https://user-images.githubusercontent.com/1262554/197861095-ae7b0262-9ad5-4561-ab79-0f22df3c6a06.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 05](https://user-images.githubusercontent.com/1262554/197861097-f028c9a7-ab75-4532-99a4-2b71a0dbdd26.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 06](https://user-images.githubusercontent.com/1262554/197861099-3cbec7ff-424b-4941-85f4-6416c8872421.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 07](https://user-images.githubusercontent.com/1262554/197861100-2372d672-3829-4660-bdbd-574f8aa927e2.jpg)

![Subtitle Workshop 7 02 R1 - GUI - 08](https://user-images.githubusercontent.com/1262554/197861101-48eeb47f-5ec1-4cf5-8216-27a592c114d1.jpg)

**Comment by bovirus** [comment]
@URUWorks 

Could you please fix the issues and update language files? Thanks.

**Comment by Little-Data** [comment]
Why do some of my translations display properly? You can refer to my translation file.
为什么我的一些翻译可以正常显示？你可以参考一下我的翻译文件。
_
Of course, there is a lot of untranslated texts, which is a software problem.
当然，还有很多未翻译文本，这是软件问题。
![Snipaste_2022-10-30_17-57-42](https://user-images.githubusercontent.com/53138165/198872865-f611c025-2fa7-48f9-bd45-26fb1c67e819.png)

**Comment by bovirus** [comment]
@Little-Data 

Thanks for the check.
I will check again.

For other GUI issues could you please confirm that appear as I reported?

**Comment by Little-Data** [comment]
For other GUI issues,I am the same as you.
对于其它GUI问题，我和你一样。

**Comment by bovirus** [comment]
@Little-Data 

English
![image](https://user-images.githubusercontent.com/1262554/198874616-f02dec85-b5be-4d8f-baa3-38b379669411.png)

Chinese
![image](https://user-images.githubusercontent.com/1262554/198874632-6a5f012c-22f2-4a2e-ac8a-1a2062c5c951.png)

Italian
![image](https://user-images.githubusercontent.com/1262554/198874642-3ec458b2-c022-4f2e-a5b4-84c4db22d43a.png)

In my configuration as you can see

in chinese "TiP" is translated and "Translation and"Text" not translated.

in italian "TiP", "Text" and "TranslatioN" are not translated.

Version used 7.02 R1.

**Comment by bovirus** [comment]
@Little-Data 

WaAbout "TiP" was an error in language file.

Some other translation error is a code problem because text is not translated and encoded in source file. Ex

  cInfo = 'Compiled at ' + {$I %TIME%} + ' on ' + {$I %DATE%} + sLineBreak +
          'Compiler version: ' + {$I %FPCVERSION%} + sLineBreak +
          'Target CPU: ' + {$I %FPCTARGET%};
  cUW   = 'uruworks.net' + sLineBreak +
          'Copyright © 2001-2022 URUWorks.' + sLineBreak +
          '© 2022 Bedazzle, CM630.';

@URUWorks 

Could you pelase check and fix these issues updating source code and langiage files? Thanks.

**Comment by bovirus** [comment]
@URUWorks 

Found another GUI translation issue

![image](https://user-images.githubusercontent.com/1262554/198875850-ff1e333d-fe18-43c6-9a17-1903e92358f1.png)

"Cancel" is not translated
Language name are untranslated.

**Comment by bovirus** [comment]
@URUWorks 

Please as max you can don't user etxt hard coded strings biut use external language strings in language file.

Ex. of hardcoded strings - File 'Utext.pas' 

  cboInput.Items.Add('Original');
  cboInput.Items.Add('Translation');

**Comment by URUWorks** [comment]
I will update it as soon as possible, thanks--
Atentamente,

 *Aldo M. Lacavalla*
 Dir. de desarrollo y nuevas tecnologías
 *URUWorks* - 100% Software Uruguayo!
 mailto: ***@***.***
 https://uruworks.net <http://uruworks.net>

 To make a donation, click the link below:

https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=uruworks%40gmail%2ecom&item_name=URUWorks&no_shipping=0&no_note=1&tax=0&currency_code=USD&lc=US&bn=PP%2dDonationsBF&charset=UTF%2d8

 As an alternative to donations, you may help us by clicking the ads on the
official site!

**Comment by bovirus** [comment]
@URUWorks 

Your sname "sounds" italian...

**Comment by URUWorks** [comment]
correct, Italian descendant :)--
Atentamente,

 *Aldo M. Lacavalla*
 Dir. de desarrollo y nuevas tecnologías
 *URUWorks* - 100% Software Uruguayo!
 mailto: ***@***.***
 https://uruworks.net <http://uruworks.net>

 To make a donation, click the link below:

https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=uruworks%40gmail%2ecom&item_name=URUWorks&no_shipping=0&no_note=1&tax=0&currency_code=USD&lc=US&bn=PP%2dDonationsBF&charset=UTF%2d8

 As an alternative to donations, you may help us by clicking the ads on the
official site!

**Comment by chenlung** [comment]
Going forward, I would suggest filing separate issues for each problem so that it's easier to keep track of and discuss.

**Comment by bovirus** [comment]
@URUWorks 

Could you pelase fix the issues reported^?

Its seems that most of them in 7.02R2 has again place.

**Comment by URUWorks** [comment]
correct, I'll try to fix them for the next update, thanks
