### ISSUE TITLE
[Submit language pack]Chinese(Simplified)

### ISSUE THREAD

**Issue by Little-Data** [URUWorks/SubtitleWorkshop#2]
(Translated by Google Translate)
Hi! I have noticed your excellent software! I used the original en-US file to translate to zh-CN Simplified Chinese. Some translations may not be very good. Thanks for the great software!
你好！我关注到了您优秀的软件！我使用原始en-US文件翻译成zh-CN简体中文。有些翻译可能不太好。感谢您提供的优秀软件！
[zh-CN.lng](https://github.com/Little-Data/My-translations/blob/main/SubtitleWorkshop/(7.0-r9)zh-CN.lng)

**Comment by URUWorks** [comment]
thanks, I'll include it in the next release, remember that since it's still in beta the lang file will change constantly :)

**Comment by Little-Data** [comment]
OK,I know.I can update the language pack if I have time. After all, I'm still in school.⌓‿⌓If you want to update the language pack faster, you can ask someone else for help.Thank you for telling me a lot.ʕ ᵔᴥᵔ ʔ

好的，我知道了。如果我有时间，我可以更新语言包。毕竟我还在上学。⌓‿⌓如果您想更快地更新语言包，您可以向别人寻求帮助。谢谢你告诉我这么多.ʕ ᵔᴥᵔ ʔ

**Comment by URUWorks** [comment]
Muchas gracias a ti ;)

**Comment by chenlung** [comment]
Maybe we can eventually have a service such as [Transifex](https://www.transifex.com) (or alternative)?
