### ISSUE TITLE
Some features that need to be improved

### ISSUE THREAD

**Issue by Little-Data** [URUWorks/SubtitleWorkshop#3]
(All translations by Google translate)
Hi! I am very happy to have discovered the new software, the following are the problems encountered during the use, I hope you can fix it, thank you!
你好！我很高兴发现了新软件，下面是使用过程中遇到的问题，希望您能修复，谢谢了！
### 01
![01-1](https://user-images.githubusercontent.com/53138165/185082597-62174601-444c-4470-890f-5f2828ebf980.png)
-
![01-2](https://user-images.githubusercontent.com/53138165/185083085-03bbe89a-750c-4235-a9e8-32c54c219185.png)
-
![01-3](https://user-images.githubusercontent.com/53138165/185083246-f7832f2b-f41c-43cd-88f8-01e8b9ce4a00.png)
-
![01-4](https://user-images.githubusercontent.com/53138165/185083637-4a58cba2-ed8c-4caa-b1ae-fd0f8fb7889f.png)
-
This I have translated in the zh-CN file, but it is not displayed in the software
这个我已在zh-CN文件中翻译完成，但它不在软件中显示

### 02
![02](https://user-images.githubusercontent.com/53138165/185085063-457da615-d4d3-4696-85b1-98ddf8d4f550.png)
### 03
![03](https://user-images.githubusercontent.com/53138165/185085426-0e614b22-afd9-4f69-955e-1298a76db161.png)
### 04
![04](https://user-images.githubusercontent.com/53138165/185085648-7801d279-6dba-4617-a436-46d4e21d2ec1.png)
### 05
Dark mode is not supported
不支持深色模式
### 06
Autosave is not supported
不支持自动保存

That's all I found, I look forward to the software getting better and better!Best wishes for you!
我发现的就这么多了，我期待着软件越来越好！万事如意！

**Comment by URUWorks** [comment]
Thank you very much for the report, I will solve everything as quickly as possible.
Saludos!

**Comment by Little-Data** [comment]
One more thing, if you want to find the subtitle file for testing, you can find it [(my-subtitle)](https://github.com/Little-Data/my-subtitle)
还有一件事，如果想找字幕文件进行测试的话，可以到 [(my-subtitle)](https://github.com/Little-Data/my-subtitle)找到。

- Most of them are  Chinese and Japanese, because I am a collector who loves anime soundtracks.
大部分是中文和日文，因为我是动漫原声带的收集者
- Made with Aegisub, including special effects styles, the file extension is .ass
使用Aegisub制作，包含特效样式，文件扩展名为.ass
- Display two subtitles at the same time
同时显示两个字幕
- Some subtitles have karaoke effect style
有些字幕有卡拉OK特效样式

**Hope these will help you** ヾ(^∀^)ﾉ
希望这些能帮助到你 ヾ(^∀^)ﾉ

**Comment by URUWorks** [comment]
Of course, it helps me to test and try to solve errors, thanks

**Comment by URUWorks** [comment]
Fixed and ready for next release.
