### ISSUE TITLE
[bug] File extension missing from export

### ISSUE THREAD

**Issue by chenlung** [URUWorks/SubtitleWorkshop#33]
1. 'File'>'Load subtitles'.
2. Choose a file.
3. 'Open'.
4. 'File'>'Save subtitles as…'.
5. Choose another name or directory.
6. 'Save'.

Result: The file name does not feature an extension.

Notes: Might be a macOS-only bug. I don't know if guidelines have since changed from Apple, but when exporting from QuickTime Pro 7, the extension is automatically added to the file name.
![File extension missing from export  QuickTime Pro 7](https://user-images.githubusercontent.com/2973439/218235971-c3e1b91f-3261-44b1-a6e7-bf645eec1f28.png)

Subtitle Workshop 7.02 r3 - Mac 10.11.6.

**Comment by URUWorks** [comment]
Ready for next release! Thanks
