### ISSUE TITLE
[bug] ANSI-encoded Latvian letters load wrong

### ISSUE THREAD

**Issue by Ejuc** [URUWorks/SubtitleWorkshop#38]
Latvian language characters ĒŖŪĪŌĀŠĢĶĻŽČŅēŗūīōāšķļžčņ in Windows-1257 mode are loaded as ÇªÛÎÔÂÐÌÍÏÞÈÒçºûîôâðíïþèò, when srt file is encoded as ANSI. Needs to be fixed!

Version 7.02 r2 (verified on win64 version).

**Comment by URUWorks** [comment]
can you attach a test subtitle?

**Comment by Ejuc** [comment]
![image](https://user-images.githubusercontent.com/50964585/232719807-f846f12b-9e9f-4671-bdef-2e854d0724de.png)
[IT'S NOT ME, I SWEAR (2008).lav.srt.zip](https://github.com/URUWorks/SubtitleWorkshop/files/11259681/IT.S.NOT.ME.I.SWEAR.2008.lav.srt.zip)

**Comment by URUWorks** [comment]
Thanks! Is now fixed for next release.
