### ISSUE TITLE
Wrong Czech subtitles codepage detected in program

### ISSUE THREAD

**Issue by majorkalina** [URUWorks/SubtitleWorkshop#42]
Hello,
first - good job. But czech srt subtitles in ANSI 1250 code page are detected as 1252 code page when opened in the project. Obviously, this cannot be changed by user action. A sample file is attached.
[Star Wars Episode IX. - The Rise Of Skywalker.zip](https://github.com/URUWorks/SubtitleWorkshop/files/10922215/Star.Wars.Episode.IX.-.The.Rise.Of.Skywalker.zip)

**Comment by URUWorks** [comment]
Fixed for the next version, thanks

**Comment by URUWorks** [comment]
@majorkalina: Can you confirm if it's fixed?
If so, I close the topic.

**Comment by majorkalina** [comment]
Czech subtitles are displayed well now.
