### ISSUE TITLE
[macOS] Latest version doesn't load

### ISSUE THREAD

**Issue by shawkynasr** [URUWorks/SubtitleWorkshop#44]
7.02 r3 Beta Mac doesn't work with the newest version of MacOS 13.2.1

应用程序“sw”无法打开。

**Comment by chenlung** [comment]
It works okay for me on 10.11.6.

**Comment by URUWorks** [comment]
The application "sw.app" can't be opened ?

**Comment by Arduingo** [comment]
In latest x86 Monterey it only shows the message "The Application "sw.app can't be opened"

**Comment by URUWorks** [comment]
https://uruworks.net/forum/index.php?topic=30.msg72

**Comment by Arduingo** [comment]
> https://uruworks.net/forum/index.php?topic=30.msg72

Thanks the chmod did the trick

**Comment by URUWorks** [comment]
great!  thanks for letting us know ;)

**Comment by URUWorks** [comment]
![macosventura](https://user-images.githubusercontent.com/19515662/224834674-bec7d363-55f1-40dd-ac2e-7976ac836333.png)

Following the steps mentioned "Subtitle Workshop" works on macOS Ventura ;)
I close the topic.
