### ISSUE TITLE
[bug]The mpv library is not loaded correctly

### ISSUE THREAD

**Issue by Little-Data** [URUWorks/SubtitleWorkshop#49]
在发行版中，mpv库未能正确改名
The mpv library was not renamed correctly in the releases

![屏幕截图 2023-05-03 170724](https://user-images.githubusercontent.com/53138165/235877017-0c961ae7-0431-4b0a-aa44-e636e4c6853a.png)

即使正确更改名称，也没有效果。无法打开视频文件
Even if the name is changed correctly, it has no effect. Cannot open video files

![屏幕截图 2023-05-03 170807](https://user-images.githubusercontent.com/53138165/235877368-63eee25e-71b2-4ce5-86b2-c1c4a0927044.png)

**Comment by URUWorks** [comment]
It's a error in the readme. 
The updated name of the library is "libmpv-2.dll".
Any additional information? You shouldn't have any problems with the library.

**Comment by Little-Data** [comment]
也许是我电脑的问题，把名称改回"libmpv-2.dll"后仍然提醒我需要去下载它。
Maybe it's a problem with my computer, after changing the name back to "libmpv-2.dll" it still reminds me that I need to download it.
即使能强行进入软件，打开视频文件将会卡住，直到自己崩溃才退出。
Even if you can force your way into the software, opening the video file will get stuck and not exit until it crashes itself.
下面是基本系统信息及软件版本：
The following is the basic system information and software version:
```
OS: Windows 10 PRO X64 
Version: 22H2 
Internal version: 19045.2006 
- 
SW version: 7.02 r3
```
对于`README.md`，您最好检查一下有没有错误，谢谢！
For `README.md`, you'd better check it for errors, thanks!

**Comment by URUWorks** [comment]
Strange, the previous version worked without problems for you.
Try download the latest library:
[libmpv2](https://github.com/URUWorks/additional-files/blob/main/libmpv/libmpv2_win64.zip)

**Comment by Little-Data** [comment]
OK!但我现在无法马上测试，过后再进行测试
OK! But I can't test it right now, and I will test it later.

**Comment by Little-Data** [comment]
感谢你的帮助。这个问题是我电脑的问题。我在其它电脑上测试均未发现异常。
Thanks for your help. This problem is my computer. I didn't find any problems when I tested on other computers.
