### ISSUE TITLE
No way to save translated text

### ISSUE THREAD

**Issue by nectricks** [URUWorks/SubtitleWorkshop#5]
I need to translate a few subtitles from EN-UK to PT-BR, and there's simply no visible way to do that in SW 7 R9. It was quite easy to save the translated file in SW 6, though.
I've just lost 5 hours of work thinking it would save both the original and translated subtitles simultaneously. I've then ran many tests and I could find no way to save them.

I'll be using SW 6 for my tasks, at the moment.

**Comment by URUWorks** [comment]
this issue will be fixed for the next release.

**Comment by chenlung** [comment]
Would it not be best doing translations when it’s in beta? Just in case things change.

**Comment by nectricks** [comment]
> Would it not be best doing translations when it’s in beta? Just in case things change.

I don't do translations a lot. I will be using SW6 anyway.
But I would never have imagined a subtitling and translating software would be released without a translation-saving option. Silly me did like 5 backup files thinking I was safe hahaha.

**Comment by URUWorks** [comment]
Fixed in v7.02 r2.
